# Model and data path
MODEL_PATH: 'weights/best.pt'
VIDEO_SOURCE_1: 'F:/CV Projects/Factory Production Line/Factory-Production-Line-Monitoring-System/video data/box.mp4'
VIDEO_SOURCE_2: 'F:/CV Projects/Factory Production Line/Factory-Production-Line-Monitoring-System/video data/pac.mp4'

# Frame processing
SKIP_FRAMES_FOR_TRACKER_1: 2
SKIP_FRAMES_FOR_TRACKER_2: 8
FRAME_WIDTH: 800
FRAME_HEIGHT: 500
FRAME_WIDTH_FOR_TRAJECTORY: 799
FRAME_HEIGHT_FOR_TRAJECTORY: 499
DEFAULT_FPS: 120

# Tracking parameters
MAX_HISTORY_FOR_SAVE_IN_DICTIONARY: 100
MAX_FRAMES_MISSING: 30
MAX_DICTIONARY_SIZE: 1000
LOG_INTERVAL_FRAMES: 30
MINIMUM_MOVEMENT_THRESHOLD: 5

# Database save interval
DATABASE_SAVE_TIME_INTERVAL: 60
LOCAL_DB_PATH: 'F:/CV Projects/Factory Production Line/Factory-Production-Line-Monitoring-System/tracking_data.db'
TURSO_DB_URL: 'libsql://trackingdata-rayan1088.aws-ap-south-1.turso.io'
TURSO_DB_TOKEN: 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NTU0Nzc4MzIsImlkIjoiM2RkYjk3MjAtZTBjMS00YjU0LTlhNjUtZmY1MjMyMGE2Nzk2IiwicmlkIjoiMDJiY2JiY2UtOGE5YS00MDZhLWFkYmQtYmVhOTFjZjdjODcxIn0.r7UydIO02UdAOSxm6ELqj6RejxrJ-_gIGKxmJYFISLdt4kyVzCwNxJsX4WVtt9VSFUQKxRKuYAZwH8N7CoTFDw'
DB_TABLE_NAMES: ['tracking_box_counts', 'tracking_cement_bag_counts']
LIMIT: 1000

# Counting lines
HORIZONTAL_LINE_1_FOR_TRACKER_1: [82, 332, 265 , 332]
HORIZONTAL_LINE_2_FOR_TRACKER_1: [298, 332, 501, 332]
HORIZONTAL_LINE_3_FOR_TRACKER_1: [536, 332, 740, 332]
COUNTING_LINE_1_FOR_TRACKER_2: [386, 299, 515, 299]

# Color constants 
BGR_BLUE: [255, 0, 0]
BGR_BLACK: [0, 0, 0]
BGR_WHITE:  [255, 255, 255]
BGR_GREEN: [0, 255, 0]
BGR_RED: [0, 0, 255]

# Drawing parameters
BBOX_THICKNESS: 1
CENTER_POINT_RADIUS: 2
TRAJECTORY_THICKNESS: 2
COUNTING_LINE_THICKNESS: 2

# Font parameters
FONT_SIZE_BBOX_LABEL: 0.3
FONT_SIZE_COUNTING_LINE: 0.5
FONT_SIZE_IN_OUT_TOTAL: 0.6
FONT_SIZE_FRAME_PRO_TRACK: 0.5
FONT_SIZE_INPUT_KEY: 0.5

FONT_THICKNESS_BBOX_LABEL: 1
FONT_THICKNESS_COUNTING_LINE: 2
FONT_THICKNESS_INPUT_KEY: 2
FONT_THICKNESS_UP_DOWN_TOTAL: 2
FONT_THICKNESS_FRAME_PRO_TRACK: 2

# Padding parameters
X_TEXT_LABEL_PADDING_COUNTING_LINE: 30
Y_TEXT_LABEL_PADDING_COUNTING_LINE: 10
TEXT_LABEL_PADDING_INPUT_KEY: 10
TEXT_LABEL_PADDING_BBOX: 10
TEXT_LABEL_OFFSET: 5

# Text position parameters
TEXT_POSITION_IN_COUNT: [20, 30]
TEXT_POSITION_OUT_COUNT: [173, 30]
TEXT_POSITION_TOTAL_COUNT: [347, 30]
TEXT_POSITION_FRAME: [20, 60]
TEXT_POSITION_FRAME_PROCESSED: [190, 60]
TEXT_POSITION_TRACKED_OB: [390, 60]
TEXT_POSITION_INPUT_KEY: [422, 490]

# OpenCV wait Time Constants
OPENCV_WAIT_KEY_DELAY: 1
WINDOW_CLEANUP_DELAY: 0.1  
